// prototype-integration/ui-src/plugins/conversation.jsx
import {
  createEffect,
  createMemo,
  createSignal,
  Index,
  onMount,
  Show,
} from "solid-js";
import { render } from "solid-js/web";
import { useHostState, useRegistry } from "../core/component.js";
import { renderMarkdown } from "../components/markdown.js";

const emptyTitle = "A workbench.\nYour way.";

function Message(props) {
  const custom = createMemo(() => {
    props.revision();
    const message = JSON.parse(JSON.stringify(props.message));
    const renderer = [...props.host.renderers.values()].find((entry) =>
      entry.matches(message)
    );
    return renderer?.render(message, props.host);
  });
  return (
    <Show
      when={custom()}
      fallback={
        <Show
          when={props.message.role === "tool"}
          fallback={
            <div
              class="message-text markdown"
              innerHTML={renderMarkdown(props.message.text || "")}
            />
          }
        >
          <details class={`evidence ${props.message.isError ? "failed" : ""}`}>
            <summary>
              {props.message.toolName || "Tool"} /{" "}
              {props.message.isError ? "failed" : "result"}
            </summary>
            <Show when={props.message.args}>
              <pre class="message-text">{JSON.stringify(props.message.args, null, 2)}</pre>
            </Show>
            <pre class="message-text">{props.message.text || ""}</pre>
          </details>
        </Show>
      }
    >
      {(node) => node()}
    </Show>
  );
}

function Conversation(props) {
  const host = props.host;
  const state = useHostState(host);
  const revision = useRegistry(host);
  const busy = () => state.bootstrap?.session.status === "running";
  const messages = () => state.bootstrap?.session.messages || [];
  const [submitting, setSubmitting] = createSignal(false);
  let textarea, form, ledger;
  let follow = true;
  function resize() {
    textarea.style.height = "auto";
    const style = getComputedStyle(textarea);
    const line = parseFloat(style.lineHeight);
    const chrome = parseFloat(style.paddingTop) +
      parseFloat(style.paddingBottom) + parseFloat(style.borderTopWidth) +
      parseFloat(style.borderBottomWidth);
    const desired = Math.max(line * 2 + chrome, textarea.scrollHeight);
    textarea.style.height = `${Math.min(desired, line * 4 + chrome)}px`;
    textarea.style.overflowY = desired > line * 4 + chrome ? "auto" : "hidden";
  }
  onMount(resize);
  createEffect(() => {
    JSON.stringify(messages());
    state.liveText;
    state.activeTool;
    busy();
    revision();
    queueMicrotask(() => {
      if (follow && ledger?.isConnected) ledger.scrollTop = ledger.scrollHeight;
    });
  });
  async function act(name) {
    host.state.patch({ error: "" });
    try {
      await host.transport.command(name);
      await host.transport.refresh();
    } catch (error) {
      host.state.patch({ error: error.message });
    }
  }
  async function submit(event) {
    event.preventDefault();
    const text = textarea.value.trim();
    if (!text || submitting() || busy()) return;
    setSubmitting(true);
    host.state.patch({ error: "", liveText: "" });
    try {
      await host.transport.command("message", { text });
      textarea.value = "";
      resize();
      await host.transport.refresh();
    } catch (error) {
      host.state.patch({ error: error.message });
    } finally {
      setSubmitting(false);
    }
  }
  return (
    <>
      <div class="section-heading">
        <h2>Working transcript</h2>
        <button
          type="button"
          disabled={busy() || !messages().length}
          onClick={() => act("reset")}
        >
          New session
        </button>
      </div>
      <div
        ref={ledger}
        class="ledger"
        aria-label="Conversation"
        onScroll={() => {
          follow =
            ledger.scrollHeight - ledger.scrollTop - ledger.clientHeight < 100;
        }}
      >
        <Index each={messages()}>
          {(message, index) => (
            <article class={`ledger-row ${message().role}`}>
              <span class="row-number">
                {String(index + 1).padStart(2, "0")}
              </span>
              <div>
                <div class="role">
                  {message().role === "user"
                    ? "You / instruction"
                    : message().role}
                </div>
                <Message message={message()} host={host} revision={revision} />
              </div>
            </article>
          )}
        </Index>
        <Show when={!messages().length}>
          <section class="empty">
            <h3>{emptyTitle}</h3>
            <p>
              Give the agent a task. Inspect its work. Swap the pieces that make
              it yours.
            </p>
            <div class="starters">
              {[
                "Read the files in this workspace and explain its structure.",
                "Create hello.txt with a short greeting, then read it back.",
              ].map((prompt) => (
                <button
                  type="button"
                  onClick={() => {
                    textarea.value = prompt;
                    resize();
                    textarea.focus();
                  }}
                >
                  {prompt} ↗
                </button>
              ))}
            </div>
          </section>
        </Show>
        <Show when={busy() || state.liveText}>
          <article class="ledger-row live">
            <span class="row-number">↳</span>
            <div>
              <div class="role">Agent / working</div>
              <div
                class="message-text markdown"
                innerHTML={renderMarkdown(
                  state.liveText || (state.activeTool
                    ? `${state.activeTool.name}\n${
                      JSON.stringify(state.activeTool.args, null, 2)
                    }`
                    : "Thinking…"),
                )}
              />
            </div>
          </article>
        </Show>
      </div>
      <form ref={form} class="composer" onSubmit={submit}>
        <textarea
          ref={textarea}
          id="prompt"
          aria-label="Your instruction"
          placeholder="Describe the work. Be specific."
          rows="2"
          required
          onInput={resize}
          onKeyDown={(event) => {
            if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
              form
                .requestSubmit();
            }
          }}
        />
        <div class="composer-actions">
          <span class="hint">⌘ / Ctrl + Enter to run</span>
          <button
            type="button"
            disabled={!busy()}
            onClick={() => act("cancel")}
          >
            Stop ■
          </button>
          <button
            type="submit"
            class="primary"
            disabled={busy() || submitting()}
          >
            Run agent ↗
          </button>
        </div>
      </form>
    </>
  );
}
export default {
  id: "ui.conversation",
  activate: (host) =>
    host.registerView("conversation", {
      title: "Conversation",
      slot: "main",
      mount: (container, host) =>
        render(() => <Conversation host={host} />, container),
    }),
};

// prototype-lit/ui-src/plugins/conversation.js
import { html } from "lit";
import { guard } from "lit/directives/guard.js";
import { repeat } from "lit/directives/repeat.js";

import { HostElement, mountElement } from "../core/component.js";

class Conversation extends HostElement {
  connectedCallback() {
    super.connectedCallback();
    this.revision = 0;
    this.unregistry = this.host.onRegistryChange(() => {
      this.revision++;
      this.requestUpdate();
    });
  }
  disconnectedCallback() {
    this.unregistry?.();
    super.disconnectedCallback();
  }
  willUpdate() {
    const ledger = this.querySelector(".ledger");
    this.follow = !ledger || ledger.scrollHeight - ledger.scrollTop - ledger.clientHeight < 100;
  }
  firstUpdated() {
    this.resize();
  }
  updated() {
    const ledger = this.querySelector(".ledger");
    if (this.follow && ledger) ledger.scrollTop = ledger.scrollHeight;
  }
  resize() {
    const textarea = this.querySelector("textarea");
    textarea.style.height = "auto";
    const style = getComputedStyle(textarea);
    const line = parseFloat(style.lineHeight);
    const chrome =
      parseFloat(style.paddingTop) +
      parseFloat(style.paddingBottom) +
      parseFloat(style.borderTopWidth) +
      parseFloat(style.borderBottomWidth);
    const desired = Math.max(line * 2 + chrome, textarea.scrollHeight);
    textarea.style.height = `${Math.min(desired, line * 4 + chrome)}px`;
    textarea.style.overflowY = desired > line * 4 + chrome ? "auto" : "hidden";
  }
  async act(name) {
    this.host.state.patch({ error: "" });
    try {
      await this.host.transport.command(name);
      await this.host.transport.refresh();
    } catch (error) {
      this.host.state.patch({ error: error.message });
    }
  }
  async submit(event) {
    event.preventDefault();
    const textarea = this.querySelector("textarea");
    const text = textarea.value.trim();
    if (!text || this.submitting || this.state.bootstrap?.session.status === "running") return;
    this.submitting = true;
    this.host.state.patch({ error: "", liveText: "" });
    try {
      await this.host.transport.command("message", { text });
      textarea.value = "";
      this.resize();
      await this.host.transport.refresh();
    } catch (error) {
      this.host.state.patch({ error: error.message });
    } finally {
      this.submitting = false;
      this.requestUpdate();
    }
  }
  message(message) {
    const renderer = [...this.host.renderers.values()].find((entry) => entry.matches(message));
    if (renderer) return renderer.render(message, this.host);
    const content = html`<pre class="message-text">${message.text || ""}</pre>`;
    return message.role !== "tool"
      ? content
      : html`<details class="evidence ${message.isError ? "failed" : ""}">
          <summary>
            ${message.toolName || "Tool"} / ${message.isError ? "failed" : "result"}
          </summary>
          ${
            message.args
              ? html`<pre class="message-text">${JSON.stringify(message.args, null, 2)}</pre>`
              : ""
          }${content}
        </details>`;
  }
  render() {
    const { bootstrap, liveText, activeTool } = this.state;
    const messages = bootstrap?.session.messages || [];
    const busy = bootstrap?.session.status === "running";
    return html`
      <div class="section-heading">
        <h2>Working transcript</h2>
        <button ?disabled=${busy || !messages.length} @click=${() => this.act("reset")}>
          New session
        </button>
      </div>
      <div class="ledger" aria-label="Conversation">
        ${repeat(
          messages,
          (_message, index) => index,
          (message, index) =>
            html`<article class="ledger-row ${message.role}">
              <span class="row-number">${String(index + 1).padStart(2, "0")}</span>
              <div>
                <div class="role">
                  ${message.role === "user" ? "You / instruction" : message.role}
                </div>
                ${guard([JSON.stringify(message), this.revision], () => this.message(message))}
              </div>
            </article>`,
        )}
        ${
          !messages.length
            ? html`
                <section class="empty">
                  <h3>${"A workbench.\nYour way."}</h3>
                  <p>
                    Give the agent a task. Inspect its work. Swap the pieces that make it yours.
                  </p>
                  <div class="starters">
                    ${[
                      "Read the files in this workspace and explain its structure.",
                      "Create hello.txt with a short greeting, then read it back.",
                    ].map(
                      (prompt) =>
                        html`<button
                          @click=${() => {
                            const input = this.querySelector("textarea");
                            input.value = prompt;
                            this.resize();
                            input.focus();
                          }}
                        >
                          ${prompt} ↗
                        </button>`,
                    )}
                  </div>
                </section>
              `
            : ""
        }
        ${
          busy || liveText
            ? html`
                <article class="ledger-row live">
                  <span class="row-number">↳</span>
                  <div>
                    <div class="role">Agent / working</div>
                    <pre class="message-text">
${
                        liveText ||
                        (activeTool
                          ? `${activeTool.name}\n${JSON.stringify(activeTool.args, null, 2)}`
                          : "Thinking…")
                      }</pre>
                  </div>
                </article>
              `
            : ""
        }
      </div>
      <form class="composer" @submit=${this.submit}>
        <textarea
          id="prompt"
          aria-label="Your instruction"
          placeholder="Describe the work. Be specific."
          rows="2"
          required
          @input=${this.resize}
          @keydown=${(event) => {
            if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
              this.querySelector("form").requestSubmit();
            }
          }}
        ></textarea>
        <div class="composer-actions">
          <span class="hint">⌘ / Ctrl + Enter to run</span
          ><button type="button" ?disabled=${!busy} @click=${() => this.act("cancel")}>
            Stop ■</button
          ><button type="submit" class="primary" ?disabled=${busy || this.submitting}>
            Run agent ↗
          </button>
        </div>
      </form>
    `;
  }
}
customElements.define("fathom-lit-conversation", Conversation);
export default {
  id: "ui.conversation",
  activate: (host) =>
    host.registerView("conversation", {
      title: "Conversation",
      slot: "main",
      mount: (container, host) => mountElement("fathom-lit-conversation", container, host),
    }),
};
